name: serverDeployment
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy to ec2
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
      uses: actions/checkout@v2   - name: deploying to the ec2 instance
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${ {secrets.EC2_SSH_KEY} }
        REMOTE_HOST: ${ { secrets.HOST_DNS }}
        REMOTE_USER: ${ { secrets.USERNAME }}
        TARGET: ${ { secrets.TARGET_DIR }}
